<template lang="pug">
MButton(
  v-bind="$attrs"
  @click="modalRef?.open"
  :disabled="!!triggerButtonDisabled"
  :disabled-tooltip="typeof triggerButtonDisabled === 'string' ? triggerButtonDisabled : undefined"
  :full-width="triggerButtonFullWidth"
  :permission="permission"
  :size="triggerButtonSize"
  :data-testid="dataTestid ? dataTestid + '-button' : undefined"
  :variant="variant"
  )
    template(#icon)
      slot(name="trigger-button-icon")

    | {{ triggerButtonLabel }}

MActionModal(
  ref="modalRef"
  :title="modalTitle"
  :action="action"
  :only-close="onlyClose"
  :ok-button-label="okButtonLabel"
  :ok-button-disabled="okButtonDisabled"
  :disable-safety-lock="disableSafetyLock"
  :modal-size="modalSize"
  :variant="variant"
  :data-testid="dataTestid ? dataTestid + '-modal' : undefined"
  @show="emit('show')"
  @hide="emit('hide')"
  @ok="emit('ok')"
  @cancel="emit('cancel')"
  )
    template(v-if="$slots['modal-subtitle']" #modal-subtitle)
      slot(name="modal-subtitle")
    template(#default)
      slot

    template(v-if="$slots['center-panel']" #center-panel)
      slot(name="center-panel")

    template(v-if="$slots['right-panel']" #right-panel)
      slot(name="right-panel")
    template(v-if="$slots['bottom-panel']" #bottom-panel)
      slot(name="bottom-panel")
    template(v-if="$slots['result-panel']" #result-panel)
      slot(name="result-panel")
    template(v-if="$slots['ok-button-icon']" #ok-button-icon)
      slot(name="ok-button-icon")

</template>

<script setup lang="ts">
import { ref } from 'vue'

import type { Variant } from '../utils/types'

import MActionModal from '../unstable/MActionModal.vue'
import MButton, { type ButtonSize } from '../unstable/MButton.vue'

export interface Props {
  /**
   * Optional: Title for the modal. Has more room than the button to describe this action.
   * @example 'Update Broadcast Details'
   */
  modalTitle: string
  /**
   * Function to execute when the ok-button has been pressed. Async functions show a loading spinner.
   * @example
   * async function doSomething {
   *  await gameServerApi.post('/someRoute', someData) // Await a request
   *  showSuccessToast('Did a thing!') // Show visual feedback
   * someSubscription.triggerRefresh() // Force an immediate data refresh
   * }
   */
  action: () => Promise<void>
  /**
   * Optional: Text label for the trigger button. Should be kept as short as possible.
   * @example 'Update'
   */
  triggerButtonLabel: string
  /**
   * Optional: Whether to disable the trigger button.
   * Set this prop to `true` to disable the trigger button or use a `string` to disable the trigger button and show a tooltip.
   * @example true // Disables the trigger button.
   * @example 'Cancel this scan job.' // Disables the trigger button and shows a tooltip.
   */
  triggerButtonDisabled?: boolean | string
  /**
   * Optional: Set the trigger button to full width.
   */
  triggerButtonFullWidth?: boolean
  /**
   * Optional: Set the size of the trigger button. Defaults to 'default'.
   * @example 'small'
   */
  triggerButtonSize?: ButtonSize
  /**
   * Optional: Select a custom color variant for the trigger button. Defaults to 'primary'.
   * @example 'warning'
   */
  variant?: Variant
  /**
   * Optional: A custom label for the pop-over modal's ok-button. Defaults to 'Ok'.
   * @example 'Update'
   */
  okButtonLabel?: string
  /**
   * Optional: Disable the 'Ok' button. Good for form validation.
   * Set this prop to `true` to disable the ok-button or use a `string` to disable it and display a tooltip.
   * @example true // Disables the ok-button.
   * @example 'Please fill out all required fields.' // Disables the ok-button and shows a tooltip.
   */
  okButtonDisabled?: boolean | string
  /**
  * Optional: Remove the safety lock from the OK button.
  */
  disableSafetyLock?: boolean
  /**
   * Optional: Hide the default 'Cancel' and 'Ok' buttons in favour of a 'Close' button. Defaults to false.
   * This automatically disables the safetyLock feature.
   */
  onlyClose?: boolean
  /**
   * Optional: Set a custom size for the modal. Defaults to 'default'.
   * @example 'large'
   */
  modalSize?: 'default' | 'large'
  /**
   * Optional: Set a permission requirement for being able to use this action.
   * @example 'api.broadcasts.edit'
   */
  permission?: string
  /**
   * Optional: Unique ID for this action that is used to generate data-testids for the button and modal.
   * This is useful for testing, as it allows you to easily find the component and related children in the DOM.
   * Note: Child element test ids are generated by appending '-button' or '-modal' to the testId.
   * @example 'update-broadcast' Child component test ids: 'update-broadcast-button' and 'update-broadcast-modal'
   */
  dataTestid?: string
}

const props = withDefaults(defineProps<Props>(), {
  triggerButtonDisabled: undefined,
  triggerButtonFullWidth: undefined,
  triggerButtonSize: 'default',
  variant: 'primary',
  okButtonLabel: 'Ok',
  okButtonDisabled: undefined,
  disableSafetyLock: undefined,
  onlyClose: undefined,
  modalSize: undefined,
  permission: undefined,
  dataTestid: undefined,
})

const modalRef = ref<typeof MActionModal>()

const emit = defineEmits(['ok', 'cancel', 'show', 'hide'])
</script>
